name: ci

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "22"

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
            INITIAL_VERSION: 1.0.0
            WITH_V: false

      - name: Set Version In package.json
        run: |
            npm pkg set 'version'='${{ steps.tag.outputs.new_tag }}'

      - name: Generate Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ghcr.io/zozman/http-heartbeat
            flavor: |
              latest=true
            tags: |
              type=raw,value=${{ steps.tag.outputs.new_tag }}
              type=sha
              type=sha,format=long

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image to GitHub Container Registries
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
